version: "3.9"

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 main:app -k uvicorn.workers.UvicornWorker
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - web-redis

  web-redis:
    image: "redis:7-alpine"
    command: redis-server --requirepass king
    expose:
      - 6379
    ports:
      - "6379:6379"
